### ISSUE TITLE
ACI seewave vs soundecology

### ISSUE THREAD

**Issue by rachel-buxton** [ljvillanueva/soundecology#4]
Hi there,

I'm using both seewave and soundecology to analyze 5 minute segments of long .wav recordings.

I calculated ACI using the "ACI" function in seewave and the "acoustic_complexity" function in soundecology (using identical parameters and recordings) and both come up with very different numbers (seewave: 142.6072, soundecology: 1723.276).  I'm confused as to why this is.  Any advice you could provide would be appreciated. I'm happy to provide data if this is a problem particular to my data set.

Also, when you describe "cluster size" (j), is this the same as the "temporal step" (Pieretti et al. 2011 Eq. 2 "j")?

Thanks so much!
Rachel

**Comment by villanueval** [comment]
Hi, sorry I missed this question. 

The differences between packakges are due to different assumptions or default values. I've written a vignette that summarizes the differences here:

http://ljvillanueva.github.io/soundecology/ACIandSeewave.html

And yes, both "j" variables are the same between soundecology and Pieretti.

**Comment by villanueval** [comment]
Closed as question answered.
